index:
    path: /
    controller: App\Controller\HomeController::index

login:
    path: /login
    controller: App\Controller\LoginController::login
  


register:
    path: /register
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    methods: [GET]
    defaults:
        template: static/signup.html.twig

postregister:
    path: /register
    controller: App\Controller\LoginController::postregister
    methods: [POST]



